### ISSUE TITLE
HAE2.0规则增加存在bug

### ISSUE THREAD

**Issue by winezer0** [gh0stkey/HaE#16]
1、对于两条规则以上的，
最后一条或两条新增加的规则不会自动保存。
删除操作也不会自动保存

2、对于原先1.5.1中能够使用的正则无法继续使用（正则中带有'号），是语法错误还是需要转义 \'转义失败。
expected <block end>, but found '<scalar>'
 in 'reader', line 228, column 21:
        regex: '(?:\"|\')(((?:[a-zA-Z]{1,10}://|//)[^\"\ ... 

  - color: magenta
    name: Path Linkfinder
    loaded: false
    regex: '(?:\"|\')(((?:[a-zA-Z]{1,10}://|//)[^\"\'/]{1,}\\.[a-zA-Z]{2,}[^\"\']{0,})|((?:/|\\.\\./|\\./)[^\"\'><,;|*()(%%$^/\\\\\\[\\]][^\"\'><,;|()]{1,})|([a-zA-Z0-9_\\-/]{1,}/[a-zA-Z0-9_\\-/]{1,}\\.(?:[a-zA-Z]{1,4}|action)(?:[\\?|#][^\"|\']{0,}|))|([a-zA-Z0-9_\\-/]{1,}/[a-zA-Z0-9_\\-/]{3,}(?:[\\?|#][^\"|\']{0,}|))|([a-zA-Z0-9_\\-]{1,}\\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml|do|jspx|htm)(?:[\\?|#][^\"|\']{0,}|)))(?:\"|\')'
    scope: response
    engine: nfa

**Comment by winezer0** [comment]
regex: '(?:\"|\')(((?:[a-zA-Z]{1,10}://|//)[^\"\'/]{1,}\\.[a-zA-Z]{2,}[^\"\']{0,})|((?:/|\\.\\./|\\./)[^\"\'><,;|*()(%%$^/\\\\\\[\\]][^\"\'><,;|()]{1,})|([a-zA-Z0-9_\\-/]{1,}/[a-zA-Z0-9_\\-/]{1,}\\.(?:[a-zA-Z]{1,4}|action)(?:[\\?|#][^\"|\']{0,}|))|([a-zA-Z0-9_\\-/]{1,}/[a-zA-Z0-9_\\-/]{3,}(?:[\\?|#][^\"|\']{0,}|))|([a-zA-Z0-9_\\-]{1,}\\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml|do|jspx|htm)(?:[\\?|#][^\"|\']{0,}|)))(?:\"|\')'

**Comment by gh0stkey** [comment]
第一个bug内部已知，刚刚修复了：https://github.com/gh0stkey/HaE/releases/tag/2.0.1
第二个bug无法复现，通过UI添加规则可以使用改规则，YAML格式如下：
```yaml
  - color: gray
    engine: nfa
    loaded: true
    name: Linkfinder
    regex: (?:"|')(((?:[a-zA-Z]{1,10}://|//)[^"'/]{1,}\.[a-zA-Z]{2,}[^"']{0,})|((?:/|\.\./|\./)[^"'><,;|*()(%%$^/\\\[\]][^"'><,;|()]{1,})|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{1,}\.(?:[a-zA-Z]{1,4}|action)(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{3,}(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-]{1,}\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml)(?:[\?|#][^"|']{0,}|)))(?:"|')
    scope: any
```
