### ISSUE TITLE
response/request body 或 response/request header 时正则无法正确匹配

### ISSUE THREAD

**Issue by ptgeft** [gh0stkey/HaE#17]
**描述错误**
当 rule 的 scope 为 `response/request body` 或 `response/request header` 时，正则无法正确匹配

**问题复现**
1. 添加如下配置
```yaml
rules:
- rule:
  - color: gray
    engine: dfa
    loaded: true
    name: test
    regex: (BWS)
    scope: response header
  type: TEST
```

2. 访问百度主页 https://www.baidu.com
3. 注意到其响应头中包含 `Server: BWS/1.1`
4. 但是 HaE 并未正确匹配
5. 当修改配置 scope 部分为 `scope: response` 时，再次访问百度主页
6. Hae 正确匹配

**相关系统说明**
- HaE 2.0.2
- BurpSuite v2021.6
- Mac OS X 10.14.6

**可能的问题代码及修补建议**
问题代码 https://github.com/gh0stkey/HaE/blob/37a907d6df4b063ef3e12bca5d94cd8818970755/src/main/java/burp/action/ExtractContent.java#L41

- scopeString 为代表请求或响应，值为 `request` 或 `response`
- scope 为正则配置，例如：当值为 `response header` 时，`(scopeString.contains(scope)` 为假，无法正确进入匹配逻辑

修补建议
如下，通过配置中的 scope 来判断作用域
```diff
- if (loaded && (scopeString.contains(scope) || scope.equals("any"))) {
+ if (loaded && (scope.contains(scopeString) || scope.equals("any"))) {
```
