### ISSUE TITLE
配置文件存在bug

### ISSUE THREAD

**Issue by safe6Sec** [gh0stkey/HaE#50]
新建rule会把已有配置清空
![image](https://user-images.githubusercontent.com/26316334/157901750-0367cc3a-3668-4056-a0a8-2a359c0f132a.png)

**Comment by safe6Sec** [comment]
同样的配置文件，mac下可用，Windows只解析出tab，无对应rule

**Comment by gh0stkey** [comment]
感谢反馈，我们测试一下回复您。

**Comment by gh0stkey** [comment]
1. 测试了一下，Windows下配置并没有被清空，只是显示0KB，但实际上打开文件是有内容的，并且新增的规则可以使用。
2. 针对问题`同样的配置文件，mac下可用，Windows只解析出tab，无对应rule`，这个问题我也没有复现出来，如果可以的话可以提供一些配置文件具体内容给我，谢谢。

**Comment by safe6Sec** [comment]
师傅稍等，等我有空录个视频

**Comment by rtfghd** [comment]
遇到同样的问题，在 `https://gh0st.cn/HaE/` 网站上copy了所有配置，并重命名到 Config2.yml中，在burp 选择 Config2.yml 配置文件后，Config2.yml 里的内容被自动重置成了如下内容

```
rules:
- rule:
  - color: yellow
    engine: nfa
    loaded: true
    name: Email
    regex: (([a-zA-Z0-9][_|\.])*[a-zA-Z0-9]+@([a-zA-Z0-9][-|_|\.])*[a-zA-Z0-9]+\.((?!js|css|jpg|jpeg|png|ico)[a-zA-Z]{2,}))
    scope: response
  type: Basic Information
- rule:
  - color: gray
    engine: nfa
    loaded: false
    name: New Name
    regex: (New Regex)
    scope: any
  type: New 0
```
