### ISSUE TITLE
关于「HaE公共规则」征集活动

### ISSUE THREAD

**Issue by gh0stkey** [gh0stkey/HaE#73]
# 关于「HaE公共规则」征集活动

## 活动背景

为了更好的为开源用户服务，现在HaE官方推出「HaE公共规则」征集活动，大家可以围绕现有公共规则进行调优改进或提交具有通用性、实战性的规则。

## 活动内容

活动时间：2022年7月至2022年12月

参与方式：在本Issue下评论提交即可

活动奖励：提交调优改进规则奖励10元红包；提交通用实战规则奖励20元红包。

活动评审方：key、0chencc、OverSpace安全团队成员

## 提交模板

提交模板以HaE正则字段为主，记得使用反引号包含。

规则：
```
Name: Shiro
Regex: (=deleteMe|rememberMe=)
Color: green
Scope: any
Engine: dfa
Sensitive: true
```

测试数据：
```
rememberMe=deleteMe
```

**Comment by sv3nbeast** [comment]
当个前排
```
color: red
engine: dfa
name: 企业微信密钥
regex: ([c|C]or[p|P]id|[a|A]pp[S|s]ecret|[c|C]orp[s|S]ecret)
scope: any
sensitive: true
```
测试数据

暂无，检测的参数名corpid     appsecret   corpsecret  准确性未知，缺乏实战收获

**Comment by gh0stkey** [comment]
@sv3nbeast 根据GIthub的信息去敏的测试数据如下：

```json
{"corpid":"wwc830525c5b018fe1", "corpsecret":"dCSk9_GdaaakC6RcVjVRO1BlLne-JPcgUrDiQS5JBbC"}
```

由于`appsecret `具有普遍性，缺少特有特征所以删除该匹配，正则变为：

```
([c|C]or[p|P]id|[c|C]orp[s|S]ecret)
```

完整规则修改为：

```yml
color: green
engine: dfa
loaded: true
name: WeCom Key
regex: ([c|C]or[p|P]id|[c|C]orp[s|S]ecret)
scope: any
sensitive: true
```

HaE测试截图如下：

<img width="490" alt="image" src="https://user-images.githubusercontent.com/24655118/178642000-a8fe9d9d-a46b-4ec5-aa5f-dcde9c67604b.png">

综上所述，收录该规则，麻烦微信联系我，发放活动奖励（20元），再次感谢。
